added material table for AdminModule. Transfer new-news.component to …
ShpakKate/Firs-app pull request #5
Opened 2023-02-13 17:29 UTC by ShpakKate

…UserModule. Fixes errors. Creation server for news

2023-02-13 19:37 UTC, burymm commented
@ShpakKate please resolve conflicts before

2023-02-14 20:55 UTC, Dewlar commented
all merge problems have been resolved in this branch.
@ShpakKate feels good ;)

2023-02-14 21:28 UTC, Dewlar requested changes
need to make a few minor edits
otherwise good

2023-02-14 21:28 UTC, Dewlar commented on src/app/admin/admin-layout/admin-layout.component.ts
> +  logout(event: MouseEvent) {
Unused parameter data

2023-02-14 21:28 UTC, Dewlar commented on src/app/components/newsitem/newsitem.component.ts
> +        switchMap(users => this.dataService.deleteNews(item)),
users is unused parameter data, so must be deleted

2023-02-14 21:28 UTC, Dewlar commented on src/app/admin/components/list-of-users/list-of-users.component.ts
> +      tap(data => {
`data` is unused parameter data
but all of the `tap`  operator is unnecessary so can be removed

2023-02-14 21:28 UTC, Dewlar commented on src/app/admin/components/list-of-users/list-of-users.component.ts
>    loadData() {
method for nothing

2023-02-14 21:31 UTC, Dewlar commented on src/app/admin/components/list-of-users/list-of-users.component.ts
>    loadData() {
sorry, wrong marker
i mean `loadData(){}` - it is the method for nothing
it is empty

2023-02-15 13:29 UTC, burymm commented on src/app/admin/components/list-of-users/list-of-users.component.ts
> +        console.log(this.dataSource.data);
also console log can be removed from prod code

2023-02-15 19:33 UTC, closed without merging